/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import React from 'react'
import Head from 'next/head'
import { getSession, useSession } from 'next-auth/react'
import Header from '../../components/Header'
import Hero from '../../components/Hero'
import Image from 'next/image'

export const getServerSideProps = async (context) => {
  const session = await getSession(context)
  const { id } = context.query

  const request = await fetch(
    `https://api.themoviedb.org/3/movie/${id}?api_key=${process.env.TMDB_API_KEY}&language=pt-BR&append_to_response=videos`
  ).then((response) => response.json())

  return {
    props: {
      result: request,
      session,
    },
  }
}

export default function Movie({ result }) {
  const { data: _, status } = useSession()
  const BASE_URL = 'https://image.tmdb.org/t/p/original/'

  // console.log(status)
  // Criar Loading

  return (
    <>
      <Head>
        <title>{result.title || result.original_title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {!status == 'unauthenticated' ? (
        <Hero />
      ) : (
        <section className="relative z-50">
          <div className="relative min-h-[calc(100vh-72px)]">
            <Image
              src={
                `${BASE_URL}${result.backdrop_path || result.poster_path}` ||
                `${BASE_URL}${result.poster_path}`
              }
              layout="fill"
              objectFit="cover"
            />
          </div>
          <div className="absolute z-50 space-y-6 inset-y-28 md:inset-y-auto md:bottom-10 inset-x-4 md:inset-x-12">
            <h1 className="text-3xl font-bold sm:text-4xl md:text-5xl">
              {result.title || result.original_title}
            </h1>
            <div className="flex items-center space-x-3 md:space-x-5">
              <button className="text-xs md:text-base bg-[#f9f9f9] text-black flex items-center justify-center py-2.5 px-6 rounded hover:bg-[#c6c6c6]">
                <img
                  src="/images/play-icon-black.svg"
                  alt=""
                  className="h-6 md:h-8"
                />
                <span className="font-medium tracking-wide uppercase">
                  Play
                </span>
              </button>

              <button
                className="text-xs md:text-base bg-black/30 text-[#f9f9f9] border border-[#f9f9f9] flex items-center justify-center py-2.5 px-6 rounded hover:bg-gray-500/20"
                // onClick={() => setShowPlayer(true)}
              >
                <img
                  src="/images/play-icon-white.svg"
                  alt=""
                  className="h-6 md:h-8"
                />
                <span className="font-medium tracking-wide uppercase">
                  Trailer
                </span>
              </button>
            </div>
          </div>
        </section>
      )}
    </>
  )
}
