import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'

import Header from '../components/Header'
import Hero from '../components/Hero'
import Slider from '../components/Slider'

export const getServerSideProps = async (context) => {
  const session = await getSession(context)

  return {
    props: {
      session,
    },
  }
}

export default function Home() {
  const { data: session } = useSession()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {!session ? <Hero /> : (
        <main>
          <Slider />
        </main>
      )}
    </div>
  )
}
