import { getProviders } from 'next-auth/react'
import Head from 'next/head'
import Header from '../components/Header'

export const getServerSideProps = async () => {
  const providers = await getProviders()

  return {
    props: {
      providers,
    },
  }
}

export default function Home({ providers }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header providers={providers} />
    </div>
  )
}
